name: Test Action

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Clean Dependencies
        run: rm -rf node_modules

      - name: Start install timer (default)
        run: echo "START=$(date +%s%3N)" >> $GITHUB_ENV

      - name: Test Action (Default Version)
        uses: ./
        id: install-default

      - name: End install timer (default)
        run: echo "END=$(date +%s%3N)" >> $GITHUB_ENV

      - name: Verify Default Installation
        run: |
          echo "Installed version: ${{ steps.install-default.outputs.osls-version }}"
          echo "Binary path: ${{ steps.install-default.outputs.osls-path }}"
          osls --version
          echo "Install time (ms): $((END-START))"

      - name: Start install timer (specific)
        run: echo "START=$(date +%s%3N)" >> $GITHUB_ENV

      - name: Test Action (Specific Version)
        uses: ./
        with:
          osls-version: '3.59.3'
        id: install-specific

      - name: End install timer (specific)
        run: echo "END=$(date +%s%3N)" >> $GITHUB_ENV

      - name: Verify Specific Installation
        run: |
          echo "Installed version: ${{ steps.install-specific.outputs.osls-version }}"
          osls --version
          echo "Install time (ms): $((END-START))"
